"""
Generate ``config.py`` for a new domain agent.
"""

from __future__ import annotations

from typing import Tuple

from sciagent_wizard.models import WizardState


def generate_config_source(state: WizardState) -> str:
    """Return the Python source for the generated agent's ``config.py``."""

    # Prepare suggestion chips
    chips_lines = ""
    if state.suggestion_chips:
        items = []
        for label, prompt in state.suggestion_chips:
            items.append(f'    SuggestionChip("{_esc(label)}", "{_esc(prompt)}"),')
        chips_lines = "\n".join(items)

    # Extra libraries from confirmed packages
    extra_libs: dict[str, str] = {}
    for pkg in state.confirmed_packages:
        pname = pkg.pip_name.replace("-", "_")
        if pname:
            extra_libs[pname] = pname

    # Bounds
    bounds_str = ""
    if state.bounds:
        items = []
        for param, (lo, hi) in state.bounds.items():
            items.append(f'    "{_esc(param)}": ({lo}, {hi}),')
        bounds_str = "\n".join(items)

    # Forbidden / warning patterns
    forbidden_str = _pattern_list(state.forbidden_patterns)
    warning_str = _pattern_list(state.warning_patterns)

    # File types
    file_types = state.accepted_file_types or [".csv"]
    ft_str = ", ".join(f'"{e}"' for e in file_types)

    source = f'''\
"""
{state.agent_display_name} — Agent configuration.

Auto-generated by the sciagent self-assembly wizard.
"""

from sciagent.config import AgentConfig, SuggestionChip

{_upper(state.agent_name)}_CONFIG = AgentConfig(
    name="{_esc(state.agent_name)}",
    display_name="{_esc(state.agent_display_name)}",
    description="{_esc(state.agent_description)}",
    instructions="",
    accepted_file_types=[{ft_str}],
    suggestion_chips=[
{chips_lines}
    ],
    logo_emoji="{_esc(state.agent_emoji)}",
    accent_color="#58a6ff",
    extra_libraries={_dict_literal(extra_libs)},
    bounds={{{bounds_str}
    }},
    forbidden_patterns=[{forbidden_str}],
    warning_patterns=[{warning_str}],
    docs_dir="docs",
    model="claude-opus-4.5",
)
'''
    return source


# ── Helpers ─────────────────────────────────────────────────────────────


def _esc(s: str) -> str:
    """Escape a string for embedding in Python source."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _upper(name: str) -> str:
    """Convert a slug to a CONSTANT_NAME."""
    return name.upper().replace("-", "_").replace(" ", "_")


def _dict_literal(d: dict) -> str:
    if not d:
        return "{}"
    items = ", ".join(f'"{k}": "{v}"' for k, v in d.items())
    return "{" + items + "}"


def _pattern_list(patterns: list[Tuple[str, str]]) -> str:
    if not patterns:
        return ""
    items = []
    for pat, msg in patterns:
        items.append(f'("{_esc(pat)}", "{_esc(msg)}")')
    return "\n        " + ",\n        ".join(items) + ",\n    "
