"""
docs_gen — Write package documentation files into the generated project.

Shared across all three output modes (fullstack, copilot_agent, markdown).
Each entry in ``WizardState.package_docs`` becomes a separate ``.md`` file,
plus an ``index.md`` that catalogues them all.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Dict, List

from sciagent_wizard.models import WizardState

logger = logging.getLogger(__name__)


def write_docs(state: WizardState, docs_dir: Path) -> List[Path]:
    """Write package documentation markdown files.

    Args:
        state: Populated wizard state with ``package_docs``.
        docs_dir: Directory to write docs into (created if needed).

    Returns:
        List of paths to written files.
    """
    docs_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []

    # Individual package docs
    for pkg_name, content in state.package_docs.items():
        filename = _safe_filename(pkg_name) + ".md"
        path = docs_dir / filename
        path.write_text(content, encoding="utf-8")
        written.append(path)
        logger.debug("Wrote doc: %s", path)

    # Index file
    index_path = docs_dir / "index.md"
    index_path.write_text(_build_index(state), encoding="utf-8")
    written.append(index_path)
    logger.debug("Wrote doc index: %s", index_path)

    return written


def _build_index(state: WizardState) -> str:
    """Build an index.md that lists all available docs."""
    lines = [
        f"# {state.agent_display_name} — Package Documentation",
        "",
        "Reference documentation for the domain-specific packages used by this agent.",
        "Each file contains installation instructions, key APIs, and usage examples.",
        "",
        "## Available Docs",
        "",
    ]

    for pkg_name in sorted(state.package_docs.keys()):
        filename = _safe_filename(pkg_name) + ".md"
        # Extract first non-empty description line from the doc
        summary = _extract_summary(state.package_docs[pkg_name])
        lines.append(f"- [{pkg_name}]({filename}): {summary}")

    if not state.package_docs:
        lines.append("*No package documentation available.*")

    lines.extend([
        "",
        "---",
        "",
        f"*Generated by the sciagent self-assembly wizard.*",
    ])

    return "\n".join(lines)


def _extract_summary(doc_content: str) -> str:
    """Extract a one-line summary from a doc file."""
    for line in doc_content.splitlines():
        line = line.strip()
        # Skip headings, blank lines, blockquotes used as description
        if line.startswith("#") or not line:
            continue
        if line.startswith(">"):
            return line.lstrip("> ").strip()[:120]
        # First real text line
        return line[:120]
    return "See documentation file for details."


def _safe_filename(name: str) -> str:
    """Convert a package name to a safe filename slug."""
    return re.sub(r"[^a-zA-Z0-9_-]", "_", name.lower())
